config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Health check for load balancers and uptime monitors
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Root route
  root 'homepage#index'

  # GraphQL API endpoint
  post 'graphql', to: 'graphql#execute'

  # Devise authentication (skipping all default routes)
  devise_for :users, skip: :all

  # Facebook Data Deletion Request Callback
  post 'facebook_data_deletion/callback', to: 'facebook_data_deletion#callback'
  get 'facebook_data_deletion/status', to: 'facebook_data_deletion#status'

  # User-related routes
  scope 'users', controller: 'users' do
    get 'sign_in', action: :sign_in, as: :users_sign_in
    get 'sign_out', action: :sign_out, as: :users_sign_out
    get 'settings', action: :settings, as: :users_settings
  end

  # Admin area routes
  namespace :admin do
    root to: 'settings#index'
    resources :settings, only: %i[index]
    resources :users, only: %i[index show]
  end

  # Main resource routes
  resources :photos, except: %i[new] do
    collection do
      get :upload
      get :organizer
      get :deselected
      get :feed, defaults: { format: :xml }
    end
  end

  resources :albums, only: %i[index show] do
    collection do
      get :feed, defaults: { format: :xml }
    end
    get :sort
  end

  resources :tags, only: %i[index show]

  # Statistics
  get 'stats', to: 'stats#index'

  # Static pages
  get 'about', to: 'pages#handler'
  get 'terms-of-service', to: 'pages#handler'
  get 'privacy-policy', to: 'pages#handler'

  # Administrative interfaces - Sidekiq web UI
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV.fetch('PHOTONIA_SIDEKIQ_WEB_USERNAME') &&
      password == ENV.fetch('PHOTONIA_SIDEKIQ_WEB_PASSWORD')
  end

  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/homepage_controller.rb
# frozen_string_literal: true

# HomepageController - displays the homepage
class HomepageController < ApplicationController
  include HomepageLoader
  def index; end
end

app/views/homepage/index.html.erb
<%
  content_for(
    :autodiscovery_link,
    auto_discovery_link_tag(:rss, feed_photos_url(format: :xml), title: Setting.site_name + ' - Photos RSS') + "\n    " +
    auto_discovery_link_tag(:rss, feed_albums_url(format: :xml), title: Setting.site_name + ' - Albums RSS')
  )
%>
<div>
  <h1>Latest photo</h1>
  <a href="<%= photo_path(@latest_photo) %>">
    <img src="<%= @latest_photo.image_url(:extralarge) %>" />
  </a>
  <div>
    <div>
      <a href="<%= photo_path(@latest_photo) %>"><span><%= @latest_photo.title %></span></a>
    </div>
    <div>
      <a href="<%= photos_path %>">See all photos...</a>
    </div>
  </div>
</div>
<hr>
<div>
  <div>
    <div>
      <h1>Random photo</h1>
      <a href="<%= photo_path(@random_photo) %>">
        <img src="<%= @random_photo.image_url(:large) %>" />
        <%= @random_photo.title %>
      </a>
    </div>
    <div>
      <h2>Most used tags</h2>
      <div>
        <% @most_used_tags.each_with_index do |tag, index| %>
          <div>
            <div>
              <a href="<%= tag_path(tag) %>"><%= tag.name %></a>
              <span><%= tag.taggings_count %></span>
            </div>
          </div>
        <% end %>
      </div>
      <a href="<%= tags_path %>">See tags page...</a>
    </div>
  </div>
</div>