config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Health check for load balancers and uptime monitors
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Root route
  root 'homepage#index'

  # GraphQL API endpoint
  post 'graphql', to: 'graphql#execute'

  # Devise authentication (skipping all default routes)
  devise_for :users, skip: :all

  # Facebook Data Deletion Request Callback
  post 'facebook_data_deletion/callback', to: 'facebook_data_deletion#callback'
  get 'facebook_data_deletion/status', to: 'facebook_data_deletion#status'

  # User-related routes
  scope 'users', controller: 'users' do
    get 'sign_in', action: :sign_in, as: :users_sign_in
    get 'sign_out', action: :sign_out, as: :users_sign_out
    get 'settings', action: :settings, as: :users_settings
  end

  # Admin area routes
  namespace :admin do
    root to: 'settings#index'
    resources :settings, only: %i[index]
    resources :users, only: %i[index show]
  end

  # Main resource routes
  resources :photos, except: %i[new] do
    collection do
      get :upload
      get :organizer
      get :deselected
      get :feed, defaults: { format: :xml }
    end
  end

  resources :albums, only: %i[index show] do
    collection do
      get :feed, defaults: { format: :xml }
    end
    get :sort
  end

  resources :tags, only: %i[index show]

  # Statistics
  get 'stats', to: 'stats#index'

  # Static pages
  get 'about', to: 'pages#handler'
  get 'terms-of-service', to: 'pages#handler'
  get 'privacy-policy', to: 'pages#handler'

  # Administrative interfaces - Sidekiq web UI
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV.fetch('PHOTONIA_SIDEKIQ_WEB_USERNAME') &&
      password == ENV.fetch('PHOTONIA_SIDEKIQ_WEB_PASSWORD')
  end

  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="apple-mobile-web-app-title" content="Photonia">
<meta name="application-name" content="Photonia">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_opengraph.html.erb
<meta name="description" content="<%= strip_tags(@photo.description_html) %>">

<meta property="og:url" content="<%= page_url %>">
<meta property="og:type" content="website">
<meta property="og:title" content="<%= @photo.title %>">
<meta property="og:description" content="<%= strip_tags(@photo.description_html) %>">
<meta property="og:image" content="<%= @photo.image_url(:large) %>">

<meta name="twitter:card" content="summary_large_image">
<meta property="twitter:domain" content="<%= request.host %>">
<meta property="twitter:url" content="<%= page_url %>">
<meta name="twitter:title" content="<%= @photo.title %>">
<meta name="twitter:description" content="<%= strip_tags(@photo.description_html) %>">
<meta name="twitter:image" content="<%= @photo.image_url(:large) %>">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (yield(:page_title) + " - " unless yield(:page_title).blank?).to_s + Setting.site_name %></title>

    <%= render partial: 'layouts/favicon' %>

    <%= render partial: 'layouts/opengraph' if @photo %>

    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js"></script>
    <%= Setting.site_tracking_code.html_safe %>

    <%= yield(:autodiscovery_link) %>

    <%= javascript_tag nonce: true do %>
      window.settings = <%= @settings.html_safe %>
      window.gql_queries = <%= @gql_queries.html_safe %>
      <% if(@gql_cached_query) %>
        window.gql_cached_query = "<%= j(@gql_cached_query.html_safe) %>"
      <% end %>
      <% if(@gql_cached_result) %>
        window.gql_cached_result = <%= @gql_cached_result.html_safe %>
      <% end %>
    <% end %>
  </head>

  <body>
    <div id='app'>
      <nav>
        <ul>
          <li><a href="<%= root_path %>"><%= Setting.site_name %></a></li>
          <li><a href="<%= photos_path %>">Photos</a></li>
          <li><a href="<%= albums_path %>">Albums</a></li>
          <li><a href="<%= tags_path %>">Tags</a></li>
        </ul>
      </nav>
      <section>
        <%= yield %>
      </section>
    </div>
    <div id='modal-root'></div>
  </body>
</html>